### PR TITLE
remove unused vendor files in advancedcontentfilter

### PR DESCRIPTION
**Pull request by Art4**
In https://github.com/friendica/friendica-addons/commit/b0ee9fdf2aafe67bb8e36e571cb6b5eef58bb3b4 the composer dependencies of the addon `advancedcontentfilter` where updated and the dependency symfony/polyfill-apcu v1.28 was removed.

```
- Removing symfony/polyfill-apcu (v1.28.0)
- Removing psr/simple-cache (1.0.1)
- Updating psr/http-message (1.1 => 2.0)
- Downgrading psr/container (2.0.2 => 1.1.2)
- Updating slim/slim (4.12.0 => 4.13.0)
- Installing symfony/polyfill-php80 (v1.29.0)
- Installing symfony/var-exporter (v5.4.35)
- Installing symfony/deprecation-contracts (v2.5.2)
- Installing symfony/service-contracts (v2.5.2)
- Installing symfony/polyfill-php73 (v1.29.0)
- Installing symfony/cache-contracts (v2.5.2)
- Updating symfony/cache (v3.4.47 => v4.4.48)
```

However the files for this (and other unused) dependencies were not deleted. I fixed this by deleting the `vendor` folder and run `composer install` again. 

I noticed this while working on PHPStan level 0 for friendica and getting a false positive error, see https://github.com/friendica/friendica/pull/14529

### CODE REVIEW

**Comment by tobiasd** [comment]
The addon repository here on github is only a mirror of the repository at git.friendi.ca. Could you please make your PR there? Thanks!

**Comment by MrPetovan** [comment]
@Art4 Thank you for your work, here's a direct link: https://git.friendi.ca/friendica/friendica-addons/pulls

**Comment by Art4** [comment]
Thanks, I wasn't able to register an account so far.

**Comment by Art4** [comment]
@MrPetovan I've registered an account but I havn't received an activation email so far. Can you take a look if there is something wrong with emails in forgejo?

**Comment by MrPetovan** [comment]
Unfortunately I don't have control over the forgejo install, @tobiasd  is it Utzer or you?

**Comment by MrPetovan** [comment]
Still no luck getting the activation email?

**Comment by Art4** [comment]
> Still no luck getting the activation email?

I tried it again but again no luck. I havn't received an e-mail either in spam to activate my account.

Feel free to use my commits to fix this issue now.

**Comment by MrPetovan** [comment]
Thanks, submitted with due credits: https://git.friendi.ca/friendica/friendica-addons/pulls/1567

**Pull request closed without merging**
