### PR TITLE
Use Exceptions for User::create

### PR DESCRIPTION
**Pull request by MrPetovan**
Follows https://github.com/friendica/friendica/pull/4054.

Related to https://github.com/friendica/friendica/issues/4041

### CODE REVIEW

**Comment by annando** [comment]
The corresponding PR is not yet merged due to an open question. I suggest that we assume that no one who is using this addon does update the system in the meantime ;-)

**Comment by tobiasd** [comment]
No, just revert it and reapply the PR, who know how long the other one is blocked in a non-blocked state.

Also please make the dependency clearer the next time.

**Comment by MrPetovan** [comment]
Please advise on how much more clear I can be than "Follows friendica/friendica#4054.".

**Comment by annando** [comment]
You could write "depends upon PR #..."

**Comment by zeroadam** [comment]
Blocked by PR #...

**Comment by MrPetovan** [comment]
Gotcha, I will use this language next time.

**Comment by tobiasd** [comment]
Yes, something like that. For me it read "follows the same directio/spiritn as the other PR was" which had a note of "I'm not merging it only because of the LEFT JOIN". This one did not have it and adding the exceptions made sense. Hence my false/confused merging this one.

When the other PR is merged. Reverting the revert should make this PR live again right?

**Comment by MrPetovan** [comment]
Yes!

**Pull request merged**
