### PR TITLE
[pledgie] Service has been discontinued since January 2018

### PR DESCRIPTION
**Pull request by MrPetovan**

### CODE REVIEW

**Comment by tobiasd** [comment]
>   * [pledgie] Service has been discontinued since January 2018

Then please commit the addon first to the deprecated addons repository and remove it afterwards from this repo.

Thanks!

**Comment by MrPetovan** [comment]
Then please merge https://github.com/friendica/deprecated-addons/pull/3 first because I'm not feeling the love from the deprecated addons repo.

**Comment by tobiasd** [comment]
Sorry I had forgotten about the PR ;-)

**Comment by tobiasd** [comment]
I'll have a look at your requested review later. There is a translation discussion that seems to be more pressing then this one ;-)

**Pull request merged**
