### PR TITLE
Leistungsschutzrecht: Optionally suppress pictures

### PR DESCRIPTION
**Pull request by annando**
There is a new config value to control the new behaviour.

Question: Where do we document this setting?

### CODE REVIEW

**Comment by MrPetovan** [comment]
In the addon README.

**Comment by annando** [comment]
I don't find any example for this.

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica-addons/blob/develop/twitter/config/twitter.config.php

And

https://github.com/friendica/friendica-addons/blob/develop/twitter/README.md

**Comment by annando** [comment]
Done.

**Pull request merged**
