### PR TITLE
Enable OAEP padding

### PR DESCRIPTION
**Pull request by MrPetovan**
Depends on https://github.com/friendica/friendica/pull/4656

### CODE REVIEW

**Comment by MrPetovan** [comment]
This has been rebased onto the latest RC changes, please merge #558 first.

**Comment by fabrixxm** [comment]
I think you need to rebase it on new develop, I'm sorry

**Comment by MrPetovan** [comment]
Not cool!

**Comment by MrPetovan** [comment]
Done.

**Comment by fabrixxm** [comment]
It's just the one commit ec15a39  ? It's correct?

**Comment by MrPetovan** [comment]
Closed, see conversation on the Friendica PR.

**Pull request closed without merging**
