### PR TITLE
Move app to src

### PR DESCRIPTION
**Pull request by Hypolite**
This PR updates addons to make them compatible with the release 3.5.2 of Friendica.

It all boils down to using namespaces to invoke the App class. Fortunately, very few addons do that and were disrupted on server running Friendica develop branch.

This PR should be merged after the 3.5.2 release.

### CODE REVIEW

**Comment by annando** [comment]
In fact only securemail really does make a problem. After the release we can remove much stuff from the other two files since they needn't to be called by commandline anymore then.

**Comment by Hypolite** [comment]
I'd rather not change this current PR but feel free to change anything you want after the 3.5.2 release.

**Comment by annando** [comment]
This was my plan.

**Comment by tobiasd** [comment]
> This PR should be merged after the 3.5.2 release.

But before the addons are tagged 3.5.2

**Pull request merged**
