### PR TITLE
CA translation pack

### PR DESCRIPTION
**Pull request by tobiasd**
Joan Bar has updated *a lot* of CA translations for various addons and added some new translations as well. Thanks <3

### CODE REVIEW

**Comment by AndyHee** [comment]
I can't help noticing something is not right with the naming of the folder.

This localization is for _Canadian French_ and not Catalan. Shouldn't the folder be named **fr-ca** ? This would be in convention with the IETF language tag.

**Comment by tobiasd** [comment]
Which file is for Canadian French? In Transifex they were posted to the Catalan language team.

**Comment by MrPetovan** [comment]
These translation are in Catalan, everything is alright.

**Comment by AndyHee** [comment]
My apologies! Yes, everything is fine.

**Pull request merged**
