### PR TITLE
Move TwitterOAuth to Composer, part 2 : StatusNet and Tumblr

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of https://github.com/friendica/friendica/issues/4116
Follow-up to #505

Simple copy/move for those addons I don't use myself to justify trying to use a more recent/different OAuth library.

### CODE REVIEW

**Comment by annando** [comment]
So you haven't had any chance to test it?

**Comment by MrPetovan** [comment]
No, but I didn't make any changes other than file paths. Feel free to check out the branch yourself.

**Comment by annando** [comment]
I'm currently hunting down a WSOD that comes from the "jot_networks" hook.

**Comment by MrPetovan** [comment]
With this PR?

**Comment by annando** [comment]
Jepp. It is somewhere in the folder ```statusnet/library```. I commented out the libraries there, so the page is loading again.

I guess you can find the origin of the error when you simply enable the "statusnet" addon on your system. It is getting late now here - and the bug seems to be in the whole class and inheritage thingy.

**Comment by MrPetovan** [comment]
You're going to laugh, my server load just exploded and I'm checking for bad blocks right now.

**Comment by annando** [comment]
That's bad.

**Comment by annando** [comment]
To buy you some time to hunt down the wsod, I reverted the two PRs. Good luck for your system!

**Comment by MrPetovan** [comment]
I saw that, good call.

**Pull request merged**
