### PR TITLE
DAV addon marked unsupported

### PR DESCRIPTION
**Pull request by tobiasd**
In the current state @hoergen mentioned it is not really useable throwing many errors and needs someone to care about it.

### CODE REVIEW

**Comment by annando** [comment]
I think we should move this addon to https://github.com/friendica/deprecated-addons

**Comment by tobiasd** [comment]
> I think we should move this addon to
> https://github.com/friendica/deprecated-addons

I don't think unsupported addons should be deprecated immediately. Maybe someone want to pick it up...

**Comment by annando** [comment]
I don't like the way this addon is working. AFAIK it isn't connected in any way with our calendar. A new CalDAV should do that, I think.

**Comment by MrPetovan** [comment]
I think it should be moved to the deprecated addons repository as well, if someone wants to pick it up we can always bring it back, but the ideal would be having only working addons in the current official addons repo.

**Comment by annando** [comment]
BTW: I think we also should get rid of those "pseudo-addons". For example I had a look at "group_text". This "addon" in reality is only the frontend for some switch that is used in the core. I think we should move all of these addons into the core.

An addon (for my understanding) is something where the whole coding is done in the addon itself.

**Comment by tobiasd** [comment]
> An addon (for my understanding) is something where the whole coding
> is done in the addon itself.

Interesting. For me it can be anything that is not entirely in the core. From a small mod to a totally new thing. So there "pseudo" things you call them, are entirely valid for me.

**Comment by annando** [comment]
Only the setting dialog is in the addon, but no functionality.

**Comment by tobiasd** [comment]
> Only the setting dialog is in the addon, but no functionality.

Then the question really is rather, why the setting is not in the user/admin settings already ;-) After that such an Addon could be deprecated.

**Pull request merged**
