### PR TITLE
[advancedcontentfilter] Ship standalone Vue 2 library with addon

### LINKED ISSUE #12054: [Advanced Content Filter] settings page - no rules, no fields, no buttons
- [X] I have searched open and closed issues for duplicates

### Bug Description

In current stable and develop versions the ACF settings page is broken. Nothing is displayed, just an empty "card".

### Steps to Reproduce

1.  go to settings -> addons -> advanced content filter

Actual Result:

grafik

Expected Result:

A working settings page. ;-)

### Platform Info

Friendica Version:
2022.10
2022.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes https://github.com/friendica/friendica/issues/12054

- The Composer Bower package stopped including the dist/vue.min.js which was required by the addon

### CODE REVIEW

**Comment by nupplaphil** [comment]
Wouldn't we probably miss security upgrades for Vue because it's no more managed? Isn't this a risk, is it?

**Review by Quix0r — APPROVED** [review]

**Comment by MrPetovan** [comment]
At this point, I don't really care anymore. I tried my best to use two different Javascript package managers and both were utterly disappointing.

I would be curious about the security risks of this particular application, though.

**Comment by nupplaphil** [comment]
Hm, sadly but I see ...

**Comment by Quix0r** [comment]
Cannot we rewrite this to a non-vuejs version?

**Comment by MrPetovan** [comment]
Probably, this addon project was a good opportunity for me to find out what Vue was about but it definitely doesn't have to be using Vue.

**Pull request merged**
