### PR TITLE
added a note of libravatar shutting down to the README of the addon

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by tobiasd** [comment]
I have put that on my ToDo list for the version after the next one. I'm still hoping someone takes care of friendica/friendica#4730 so that there is a 3.6.1 before the 2018.5, so that we can move the addon out of the repository with the 2018.8 around the time when the service is stopped.

**Comment by MrPetovan** [comment]
Fair enough, did you make your hope clear in the Friendica Developers forum? I probably can take a look at it in the upcoming days.

**Comment by tobiasd** [comment]
> Fair enough, did you make your hope clear in the Friendica Developers
> forum? I probably can take a look at it in the upcoming days.

Well, @annando himself announced that issue to be blocker for the release... but there might have been a squirrel or something.

**Comment by MrPetovan** [comment]
Damn squirrels. It is spring, though, so I expect the squirrel population to be exploding soon.

**Pull request merged**
