### PR TITLE
[morechoice] Add important sexual preference

### PR DESCRIPTION
**Pull request by m4sk1n**
I feel discriminated

### CODE REVIEW

**Comment by tobiasd** [comment]
How is that a sexual preference? I know rule 34, but for this o.O at least add a similar line for those that have the kink to forces guys to use Linux. And even then, the list will get really long if all the kinks is getting included. :-1:

**Comment by m4sk1n** [comment]
I would like to apologise to people I offended by not specifying ‘forcing boys to switch to Linux’ too. I feel so sorry, it wasn’t intended.

**Comment by m4sk1n** [comment]
There is a difference between `Forcing girls/boys to switch to Linux` and `Forcing people to switch to Linux` ‘Forcing boys to switch to Linux’ is definitely not my sexual preference.

**Comment by MrPetovan** [comment]
I guessed as much, but this a "More Choice" addon, which means not all choices will be relevant to you personally.

**Comment by MrPetovan** [comment]
More than a year without a follow-up, closing for now.

**Pull request closed without merging**
