### PR TITLE
Fix Issue #2103 - Enable PSR-2 coding standards for Friendica addons

### PR DESCRIPTION
**Pull request by Hypolite**
Convert all the PHP files formatting to the PSR-2 standards. No change
has been made to the functionalities, and any change in behavior is not
expected.

The files have been converted using util/php-cs-fixer.phar and the
config
file is .php_cs. The project-wide conversion can be run again with the
following command:

> php util/php-cs-fixer.phar fix .

Most of the changes are whitespace conversion from tabs to spaces.

Fix friendica/friendica#2103 for Friendica addons files.

### CODE REVIEW

**Comment by annando** [comment]
I must confess that I prefer tabs.

And I have another problem with this pull request: Since all files are touched in every single line, I guess that many people with some local changes in the addons will have massive merge conflicts.

**Comment by tobiasd** [comment]
As nice as these tools are, but this is nuts to change over 1500 files in one commit.

**Comment by Hypolite** [comment]
Fair enough, I'll update the files on an addon basis if I work on any of them, and I strongly encourage you to do the same.

@annando: I'll refer you to #2103 for discussion around the standards themselves.

**Comment by tobiasd** [comment]
Yes, much better way ;-) and the same we do with the doxygen information.

**Pull request closed without merging**
