### PR TITLE
[langfilter] Fix typos

### PR DESCRIPTION
**Pull request by urbalazs**

### CODE REVIEW

**Review by MrPetovan — COMMENTED** [review]
Thank you for you work, however these translation strings don't need to be corrected for typos since translations are created in Transifex. If anyone sees this, it means that the langage they are browsing Friendica in is missing some translations.

The problem if we merge your changes is that new translations in all languages will have to be submitted for the same text since it will count as a new translation string for Transifex.

As such, I have to decline your PR, thank you for your understanding.

**Comment by urbalazs** [comment]
@MrPetovan I can change **all occurrences** of `writen` to `written` and `specifed` to `specified` in all files, including the `messages.po` and `strings.php` in the language folders. In this case the existing translations won't be broken.

After this change, you can update the translation source as well as the translations on Transifex. The Transifex client supports this:

```
$ tx push --help
  -s, --source          Push the source file to the server.
  -t, --translations    Push the translation files to the server
```

What do you think?

**Comment by MrPetovan** [comment]
This sounds good, but I do not have good enough Transifex credentials to do this. The only person I know with admin rights is @tobiasd.

**Comment by tobiasd** [comment]
The transifex client (tx) had never worked as expected for the directory structure of the Friendica project. If they improved it, it might be worth looking at the client again.

**Pull request closed without merging**
