### PR TITLE
[communityhome] Remove active users feature

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes https://github.com/friendica/friendica/issues/4555

### CODE REVIEW

**Comment by annando** [comment]
Most of the queries in this addon are extremely intense. I suggest rebuilding that addon so that it only shows the community page, not more.

**Comment by MrPetovan** [comment]
Sure, but not for the 3.6 release though.

**Comment by annando** [comment]
I'm unsure. Problem is that the two queries with the likes and the photos are so intense, that they kill every server that is a little bit larger. So it only works on small servers with few users.  But there this addon doesn't make sense.

**Comment by MrPetovan** [comment]
We can retire the addon altogether as well.

**Comment by annando** [comment]
Possibly this would be the best. But we should not only set the special comment in the header, but also we should disable the functionality as well.

**Comment by MrPetovan** [comment]
So we keep this PR and I just add the deprecated header?

**Comment by annando** [comment]
I would prefer adding some ```return``` to the beginning of the functions. This can be done in this PR.

**Comment by MrPetovan** [comment]
I don't see the point, if node admins want to try the addon, they can, and if it's too slow, they can deactivate it. I removed a feature whose query was triggering an error, but the rest is fine, even if it's slow.

**Comment by annando** [comment]
I see the problem that people try it when their server is small enough for it. But it will be slower and slower. And since many regular users won't see the front page, they won't recognize the loss of speed.

When - eventually - I will do the new stuff with the item table, I will massively remove functionality in that addon anyway :-)

**Comment by MrPetovan** [comment]
But since it's now unsupported, most node admins won't be able to enable it anyway.

**Comment by annando** [comment]
Okay, let's see what will happen.

**Pull request merged**
