### PR TITLE
Moved widgets and remote permissions to the deprecated addons

### PR DESCRIPTION
**Pull request by annando**
They are marked as deprecated and it doesn't make sense to continue working at them.

### CODE REVIEW

**Comment by tobiasd** [comment]
Will you add them to the deprecated addon repo, or shall I do it?

**Comment by tobiasd** [comment]
Do we have to adopt something with the CI?

**Comment by annando** [comment]
The deprecated addon repository on github is readonly, so I created a PR on git.friendi.ca for this.

BTW: How can I fix the check?

**Comment by tobiasd** [comment]
I've just merged it there :) and removed the resource from the translation pipe.

**Comment by annando** [comment]
How can I restart the check?

**Comment by nupplaphil** [comment]
I'll fix the test in the next hours, so just ignore it for now.. Either I have to make the xgettext more robust or exclude moved addons :)

**Comment by annando** [comment]
So @tobiasd or you can merge this one here?

**Comment by tobiasd** [comment]
> How can I restart the check?

At the drone CI server, once you are logged in.

> So @tobiasd or you can merge this one here?

If @nupplaphil does not need it for testing the improvements to the checks, this PR can be merged from my POV yes.

**Comment by nupplaphil** [comment]
@tobiasd  yep, go for it :-)

**Comment by nupplaphil** [comment]
@tobiasd / @annando  - fixed :D
see https://github.com/friendica/friendica-docker-ci/pull/7

**Pull request merged**
