### PR TITLE
Move Object\Image static methods to Util\Images

### PR DESCRIPTION
**Pull request by MrPetovan**
Depends on https://github.com/friendica/friendica/pull/7777

### CODE REVIEW

**Comment by MrPetovan** [comment]
Please don't forget about this.

**Comment by annando** [comment]
Can you enlighten me? Why doesn't it currently throws an error?

**Comment by MrPetovan** [comment]
Because I left the deprecated method in order not to throw an error.

**Comment by annando** [comment]
Ah okay.

**Pull request merged**
