### PR TITLE
[cookienotice] Fix wrong type-hint in hook function cookienotice_page_content_top

### LINKED ISSUE #11695: Friendica WSoD caused by cookienotice addon
I do not know how to continue. For two days I've had a WSoD under the domain etiketi.de under which Friendica is running.
I rule out that the error is caused by a git pull because my Friendica continues to run normally under Twidere. What I suspect is that something broke during the last storage space optimization on the server.
I can't find anything in the logs either, does anyone have a tip or an idea where I could look further?
There is either something wrong with the database or with the website.

### PR DESCRIPTION
**Pull request by MrPetovan**
- Address https://github.com/friendica/friendica/issues/11695#issuecomment-1173006420

Probably fixes https://github.com/friendica/friendica/issues/11695

### CODE REVIEW

**Comment by Quix0r** [comment]
Mostly the `$b` name has confused me. Cannot we make a naming-convention here, e.g. if it is HTML code, use `$body` (`$o` for historical reasons but that doesn't need change), `$data` if it is an array? At least not `$b` everywhere.

**Comment by MrPetovan** [comment]
Sure, go ahead.

**Comment by Quix0r** [comment]
> Sure, go ahead.

I will do it more in a controlled fashion. :-)

**Comment by nupplaphil** [comment]
Somewhere in the future (:D) I do want to rewrite the add-on classes at all .. to make them testable, like for the s3 storage classes .. and to avoid DB loadings and with type safe parameters depending on the hook calls not on the Hook class itself

**Comment by MrPetovan** [comment]
How do you plan on doing the last part?

**Comment by nupplaphil** [comment]
Using the [observer pattern](https://sourcemaking.com/design_patterns/observer/php) and passing concrete, event specific, interfaces as parameters.

Observer = Addon-Functions
Subject = Hooks

And inside the Addon-constructor, I add the the functions as observers into the subjects. So no need of any DB call and I can customize observer and subjects as I like, because I will introduce a common interface for all addons :)

I must confess it's just inside my brain now, so I'm not sure about the pitfalls .. yet :D

**Comment by MrPetovan** [comment]
We still need a DB call to figure out all the addons that need to be instantiated, right? And then they can subscribe to any hook they need. I'm looking forward a prototype implementation.

**Comment by Quix0r** [comment]
In my old `mailer` software I cached these hooks (I called them filters) to speed up the registration a little, so it doesn't have to go through all "hook" registrations but just read the database table and fill the "filter" array. Maybe @nupplaphil you can grab a few ideas: https://git.mxchange.org/?p=mailer.git;a=blob;f=inc/filter-functions.php;h=de21a6fd9c69a8fe4e1d0e050fe5ccc158ced7b0;hb=refs/heads/0.2.1-FINAL

**Pull request merged**
