### PR TITLE
[securemail] Update Composer dependencies

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes https://github.com/friendica/friendica/issues/6629

This is a prospective fix, can @tobiasd please pull this branch and test this addon as I don't have a PGP key to test it. I just successfully tried to enable it on my install.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I take this back, updating the phpseclib version didn't remove the `create_function` call.

**Comment by MrPetovan** [comment]
Actually it should suppress the notice message, see https://github.com/phpseclib/phpseclib/issues/1293#issuecomment-415033946

**Comment by tobiasd** [comment]
Checked out, lets see what happens :-)

**Comment by tobiasd** [comment]
Sending out notification mails now does not work because of

> Uncaught Error: Class 'OpenPGP' not found in /.../addon/securemail/securemail.php:162

**Comment by MrPetovan** [comment]
Thanks, please pull and try again?

**Comment by tobiasd** [comment]
Seems to be working. @fabrixxm are you fine with the changes?

**Pull request merged**
