### PR TITLE
[twitter] Update abraham/twitteroauth dependency

### PR DESCRIPTION
**Pull request by nupplaphil**
Addresses https://github.com/friendica/friendica/issues/10301#issuecomment-900419188
Because we bumped the minimum PHP version to 7.2, it's now fully compatible :-)

(outlook for 2021.12..)

### CODE REVIEW

**Comment by annando** [comment]
Have you checked if the new version is fully compatible? This version bump is really high.

**Comment by nupplaphil** [comment]
I checked the constructors and checked parts of the call process after it, but tbh I thought it's better to wait after the release and directly test it on my node with the dev branch :)

**Review by MrPetovan — COMMENTED** [review]
No backward-incompatible change to be wary of?

**Comment by annando** [comment]
I would had a better feeling when someone™ could install it on their machine and perform some tests.

**Comment by nupplaphil** [comment]
That's my plan! I'm already using twitter, so I'll do some tests, but after the release :)

--> I change it to draft :)

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
Branch is now in use, let's have a look ;D

**Comment by nupplaphil** [comment]
ready ;-)

**Pull request merged**
