### PR TITLE
Remove reference to library/langdet folder

### PR DESCRIPTION
**Pull request by MrPetovan**
This PR should ony be approved after this one: https://github.com/friendica/friendica/pull/3743

### CODE REVIEW

**Comment by annando** [comment]
Could you change the "require_once" to an "include_once"? Then this change should work on both, "master" and "develop" branch.

**Comment by Hypolite** [comment]
I'd rather not, it would emit a warning in the logs each time the plugin is loaded if the library isn't in `library`  anymore, which is the goal since we don't maintain multiple versions branch of Friendica at once.

**Comment by annando** [comment]
So what do we do?

**Comment by Hypolite** [comment]
I seem to remember we already had a breaking change between the library folder and the vendor folder affecting addons, how did we do the first time?

Otherwise we release a new version of the addon repo along the next Friendica version the library change is present.

**Comment by tobiasd** [comment]
We tag the addon repo (now again) so after the release, who runs too fresh addons should also update the main repo.

**Comment by annando** [comment]
Merging this is a problem. The addon won't work with the master branch anymore from now on.

**Comment by tobiasd** [comment]
On Thu, 05 Oct 2017 09:32:13 +0000 (UTC)
Michael Vogel <notifications@github.com> wrote:

> Merging this is a problem. The addon won't work with the master
> branch anymore from now on.

The 3.5.3 version of the addons was tagged before the PR was merged. You should checkout the 3.5.3 versions of the addons if you want to use version 3.5.3 core (master).

But my solution for the langdetect problems would be reverting both of the PRs.

-- 
Web ............ www.diekershoff.net         
~friendica ..... tobias@social.diekershoff.de     
PGP-ID ......... 0x25FE376FF17694A1

**Pull request merged**
