### PR TITLE
Fix phpstan error level 0 part2

### PR DESCRIPTION
**Pull request by Art4**
Part 2 of https://github.com/friendica/friendica-addons/pull/1367

Requires merge of:

- [x] #1368

### CODE REVIEW

**Comment by Art4** [comment]
This PR is ready for review, but requires #1368.

**Comment by Art4** [comment]
@MrPetovan This PR is ready for review. I fixed the message.po in https://github.com/friendica/friendica/pull/14571

**Comment by nupplaphil** [comment]
Prepared at https://git.friendi.ca/friendica/friendica-addons/pulls/1577

**Comment by MrPetovan** [comment]
It is pretty funny for me to see PHPStan wrangle this sometimes ancient code.

**Comment by MrPetovan** [comment]
Merged on Gitea

**Pull request closed without merging**
