### PR TITLE
Replaced goaway() with System::redirect()

### PR DESCRIPTION
**Pull request by nupplaphil**
Because of https://github.com/friendica/friendica/pull/5907

### CODE REVIEW

**Comment by annando** [comment]
I'm confused by this PR. Isn't something like this already accepted?

**Comment by MrPetovan** [comment]
🚨 Conflicts 🚨

**Comment by tobiasd** [comment]
@nupplaphil there are conflicts in this PR

**Comment by nupplaphil** [comment]
wait .. what .. sorry I really oversaw this PR .. just a minute

**Pull request merged**
