### PR TITLE
blockbot: Adding new bots to the blocklist

### PR DESCRIPTION
**Pull request by annando**
Some new bots are added.

### CODE REVIEW

**Comment by MrPetovan** [comment]
FYI: https://social.mootech.eu/@maxine/102412789235076104

**Comment by annando** [comment]
I already had seen that. I was considering adding that agent to the block list as well. But in fact we already are having a working server block mechanism.

**Comment by MrPetovan** [comment]
Yes, but this crawler block would apply to any server running the Gab social software.

**Comment by annando** [comment]
Yeah, I see the benefit. I only don't want to hardcode this. So possibly we can add some configuration.

**Comment by MrPetovan** [comment]
Fair enough.

**Comment by MrPetovan** [comment]
@tobiasd Thanks for the merge, but if I understand @annando 's process correctly, I think he wanted to have a permanently-open PR to keep adding more bots without having to submit a PR each time. He should have used the Draft PR feature of course, but so far he seems to have been unable to find the button.

**Comment by tobiasd** [comment]
I remember he had written a note about that in the last PR, but as it was missing in this PR I thought that was only with the initial collection of bots.

**Comment by MrPetovan** [comment]
I don't blame you, and you may even be right in this instance.

**Comment by annando** [comment]
I was asking myself how we could handle this. Possibly we can do a merge whenever the list grew significantly or so. 

P.S.: I used the draft thingy in some previous PR if you might remember :grimacing:

**Pull request merged**
