### PR TITLE
advancedcontentfilter: Add language values to filter fields

### PR DESCRIPTION
**Pull request by annando**
fixes issues https://github.com/friendica/friendica/issues/10052 and https://github.com/friendica/friendica/issues/10136

The language of a post is now converted into a format that can be filtered.

### CODE REVIEW

**Comment by MrPetovan** [comment]
The advanced content filter doesn't hide individual posts, it still will collapse the content only based on the rules. While it does address friendica/friendica#4869, it is unrelated to friendica/friendica#10052 or friendica/friendica#10136.

**Review by MrPetovan — APPROVED** [review]

**Comment by annando** [comment]
Okay. I must admit, that I don't use that addon :-)

**Comment by AlfredSK** [comment]
It's cool. You should try it. :-)

**Comment by MrPetovan** [comment]
It uses the same hook as nsfw and langfilter.

**Pull request merged**
