### PR TITLE
Move TwitterOAuth to composer Part 1: Twitter

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of https://github.com/friendica/friendica/issues/4116

I'm trying to get rid of `library/twitteroauth.php`, however it's a dependency for 3 addons, `statusnet`, `tumblr` and `twitter`.

A newer version of the library exists but I didn't want to put it in the Friendica main composer dependencies since it's only used in addons.

So yes, yes I did.

I created a `composer.json` for addons.

Yes, this means more Composer install shenanigans, but I figured that everybody running develop had their update script on lock by now, right?

This gets rid of CodeBird in the Twitter addon, another dependency used by a couple of addons.

### CODE REVIEW

**Comment by annando** [comment]
Have you tested that the picture upload is really working?

**Comment by tobiasd** [comment]
So far every addon creator who wanted to use composer has done so on a per addon basis. Will this per addon composer be compatible with the composer for the entire core addons?

**Comment by MrPetovan** [comment]
@annando: I was going to ask you the same question. The picture upload happens only when a Friendica post contains an `[attachment]type=image` tag, and I wasn’t able to produce one either with the image browser nor with the attachment button in the new post jot.

Is there an automatic post I wouldn’t know about that generates public posts with image attachments?

@tobias: Actually the current Composer structure is only be used by the Twitter addon, so it’s a good argument for moving it inside if the addon. Initially I thought that multiple addons shared a dependency on TwitterOAuth and Codebird, so I didn’t want to have the dependency duplicated since we ship all addons together anyway.

However StatusNet extends from a specific version of TwitterOAuth that isn’t available through Packagist, and Tumblr even has it’s own modified `TumblrOAuth` file.

**Comment by annando** [comment]
Doing a post with a single picture should work great. I'm doing this with posts from the API that contain pictures.

**Comment by annando** [comment]
See my post https://pirati.ca/display/ec054ce7425a6cd25527cb6236724404 for a post that had been sent to Twitter. So you could try to create some test post that is looking the same.

**Comment by MrPetovan** [comment]
Your post doesn't have any `[attachement]` either in its body, I'm not sure it would be picked up for image upload by the twitter addon, I have to make some closed tests.

**Comment by MrPetovan** [comment]
@tobiasd @annando I'm surprised none of you tried to dissuade me to add a addon-wide composer setting, I guess I'll have to dissuade myself! 😋

**Comment by annando** [comment]
I hope it still will be posted as picture - since this one did: https://twitter.com/heluecht/status/957334146111737856

**Comment by MrPetovan** [comment]
Twitter itself transforms image links at the end of the body into attached pictures, so I'm not sure we actually did the uploading.

**Comment by annando** [comment]
We did, trust me.

**Comment by MrPetovan** [comment]
Ok, the image link triggers the image upload, let's test if it works now.

**Comment by MrPetovan** [comment]
Upload works as expected, let's test the status update

**Comment by MrPetovan** [comment]
Success, I'll move the TwitterOAuth lib in the twitter addon now.

**Comment by MrPetovan** [comment]
After fiddling with a couple systems meant to manage optional plugins dependencies, I finally settled for the explicit dependencies commit.

This isn't a red alert anymore, everyone at ease.

**Pull request merged**
