### PR TITLE
Plugin moved to src

### PR DESCRIPTION
**Pull request by zeroadam**
include/plugin.php was moved to src Addon and Theme classes.

### CODE REVIEW

**Comment by MrPetovan** [comment]
There are many instances of `plugin` in documentation files, hook names, addon function names and translation strings (you don't need to edit the *.po or strings.php files)

**Comment by zeroadam** [comment]
I'm going to pull this back. I am going to base it on develop (now that we have it) and continue the work regarding renaming the functions in all the addons.

I really didn't expect this work to be as large as it turned out to be!!! :worried:

**Comment by MrPetovan** [comment]
Sorry about that...

**Comment by zeroadam** [comment]
No worries! As you know I use a gui program for git mostly, and it sometimes creates merge commits when I rebase, so it was mostly me making my branch messy. I have since made things nice locally, but figure it better to wait until i have more of the work done to submit PRs :smile:

**Pull request closed without merging**
