### PR TITLE
Fix phpmailer compatibility with latest stable friendica

### PR DESCRIPTION
**Pull request by kecalcze**
Develop not work with actual friendica master. I just added 2nd  param to ` Config::get` call.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Please use `friendica/friendica-addons:master` if you are using `friendica/friendica:master` as well. Both branches are supposed to work together, like both `develop` branches are supposed to work together.

**Comment by MrPetovan** [comment]
Develop Addons aren't supposed to work with latest stable Friendica. Please use latest stable Addons as well.

Although your changes don't seem to be specific to any Friendica version in particular.

**Comment by kecalcze** [comment]
I would like to, but i want to use SMTP plugin which is only in develop right now. But thx for info.

**Comment by MrPetovan** [comment]
Sorry for the inconvenience. I merged this PR because it actually wasn't specific to the Friendica version you are using it with.

For the other addon on develop not working with the latest Friendica stable, this will need to remain a local hack however.

**Pull request merged**
