### PR TITLE
[various] Convert connector/addon_settings hook functions to the new data format

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of https://github.com/friendica/friendica/issues/10978

Depends on https://github.com/friendica/friendica/pull/11014

### CODE REVIEW

**Comment by MrPetovan** [comment]
Updated after https://github.com/friendica/friendica-addons/pull/1212 was merged

**Comment by annando** [comment]
This PR is currently based on the develop branch.

**Comment by MrPetovan** [comment]
Base changed.

**Comment by annando** [comment]
I can't check 147 files. So the question is more if you have tested it.

**Comment by MrPetovan** [comment]
Yes, I've enabled all the addons that provide settings, whether for regular addons or connector addons, and tested that the config can still be changed. I tested some OAuth-based connectors further because they have a more complicated configuration flow, I even set up a GNU Social account to test the statusnet connector.

**Pull request merged**
