### PR TITLE
Cleanup implementation of langfilter_prepare_body, and fix a typo

### PR DESCRIPTION
**Pull request by strk**
I'd actually want to add a new setting to restrict filtering to posts for which the language guessers has a minimum confidence

### CODE REVIEW

**Comment by strk** [comment]
Minimum confidence in language detection support added. @tobiasd let me know if you prefer a squash-rebase of all of this.

**Comment by tobiasd** [comment]
As you have introduced new strings for the translation, could you run

    ../../util/run_xgettext.sh -s

in the langfilter directory (assuming that is $friendica/addon/langfilter) to regenerate the addons messages.po file and include it to the PR?

I have only scratched together the initial version of the addon, but I'm not using it myself. So feel free to enhance it as you feel appropriate :-)

**Comment by strk** [comment]
Translation file change pushed.
How much does it take for it to get to transifex ?

About enhancements... if you give me write access I can avoid
bothering you on next one.

**Comment by tobiasd** [comment]
It usually takes 24h till the automatic update on the transifex side.

Direct writing is bad, there should be someone else to at least look over the code ;-) PRs don't really bother me. It's more that I don't develop this addon actively. So you can enhance it in ways you seem fitting.

**Pull request merged**
