### PR TITLE
remove include/datetime.php requirement

### PR DESCRIPTION
**Pull request by rabuzarus**
`include/datetime.php` isn't available anymore in friendica core develop

### CODE REVIEW

**Comment by zeroadam** [comment]
@rabuzarus BTW, I have been unable to see this in my profile, though I have it enabled. I know it is something to do with the differences between vier and Frio. And of course, I am not skilled enough in themes to make it work. You might see I have some commented code in the addon where I tried to correctly build the div needed. Could you look into this?

**Comment by MrPetovan** [comment]
@zeroadam See what?

**Comment by zeroadam** [comment]
Oops sorry. I meant the membersince

**Comment by rabuzarus** [comment]
@zeroadam 
Have a look at https://github.com/friendica/friendica-addons/pull/519

**Pull request merged**
